name: demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: 获取 git 差异
      id: git-diff
      run: |
        echo "::set-output name=diff::$(git diff HEAD^ HEAD)"

    - name: 读取 git 差异
      run: |
        echo "开始读取 git 差异"
        python -c "
        diff = '${{ steps.git-diff.outputs.diff }}'
        print(diff)
        "
        echo "git 差异读取结束"
