name: demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 运行 shell 脚本
      run: |
        echo "开始运行 shell 脚本"
        # 在这里编写您的 shell 脚本
        echo "Hello, world!"
        echo "shell 脚本运行结束"
